apps/books_app/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^login$',views.login,name='login'),
    url(r'^register$',views.register,name='register'),
    url(r'^reg_home$',views.reg_home,name='reghome'),
    url(r'^logout$',views.logout,name='logout'),
    url(r'^newauthor$',views.newauthor,name='newauthor'),
    url(r'^newbook/(?P<id>\d+)$',views.newbook,name='newbook'),
    url(r'^add$',views.add,name='add'),
    url(r'^books$',views.books,name='books'),
    url(r'^review/(?P<id>\d+)$',views.review,name='review'),
    url(r'^users/(?P<id>\d+)$',views.users,name='users'),
    url(r'^showAdd$',views.showAdd,name='showAdd'),
    url(r'^update/(?P<id>\d+)$',views.update,name='update')
]

books/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('apps.books_app.urls',namespace='books'))
    #url(r'^', include('books_app.urls'))
]

apps/books_app/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import bcrypt
from django.db import models
import re
EMAIL_REGEX=re.compile(r"(^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$)")


# Create your models here.

class userDBManager(models.Manager):
      def login(self, postData):
          errors=[]
          ret_user=userDB.objects.filter(email=postData['email'])
          if ret_user:
              userFound=userDB.objects.get(email=postData['email'])
              password=postData['password'].encode()
              # Hash a password for the first time, with a randomly-generated salt
              hashed = bcrypt.hashpw(password, bcrypt.gensalt())
                # Check that a unhashed password matches one that has previously been
                #   hashed
              if bcrypt.hashpw(password, hashed) == hashed:
              #if (postData['password']==userFound.password):
                  print userFound
                  print "Running a login function!"
                  return(True,userFound)
              else:
                  errors.append("Couldnt login")
                  return(False,errors)
          else:
              errors.append("Couldnt login")
              return(False,errors)
         # print "If successful login occurs, maybe return {'theuser':user} where user is a user object?"
         # print "If unsuccessful, maybe return { 'errors':['Login unsuccessful'] }"
      def register(self, postData):
          errors=[]
          print postData
          if(len(postData['first_name'])<=2 or len(postData['last_name'])<=2):
              print "Name is not entered"
              errors.append("Name has to be atleast 2characters!")
          if( (len(postData['email'])<=0) or (len(postData['email'])>120) or (not EMAIL_REGEX.match(postData['email'])) ):
              print "email has to entered as test@tesmail.com"
              errors.append("Please enter email ")
          if(len(postData['password'])<=8):
              print "password less than 8characters"
              errors.append("Password needs to be 8 characters long")
          if(postData['password']<>postData['confirm_pwd']):
              print "both passwords do not match"
              errors.append("Please confirm password")
          if errors:
              print "not created"
              return(False,errors)
          else:
              ret_user=userDB.objects.filter(email=postData['email'])
              if ret_user:
                  errors.append("Please use different login info!")
                  print "Please use different login info!"
                  return(False,errors)
              print "inside save"
              password=postData['password'].encode();
              hashed = bcrypt.hashpw(password, bcrypt.gensalt())
              newUser=userDB(first_name=postData['first_name'],last_name=postData['last_name'],email=postData['email'],password=hashed)
              newUser.save()
              print "after save"
              return(True,newUser)

# Create your models here.
class userDB(models.Model):
    # First Name - Required; No fewer than 2 characters; letters only
    # Last Name - Required; No fewer than 2 characters; letters only
    # Email - Required; Valid Format
    # Password - Required; No fewer than 8 characters in length; matches Password Confirmation
    first_name = models.CharField(max_length=45)
    last_name = models.CharField(max_length=45)
    password = models.CharField(max_length=100)
    email=models.CharField(max_length=50)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

    objects=userDBManager()

class Author(models.Model):
     name = models.CharField(max_length=45)
     created_at = models.DateTimeField(auto_now_add = True)
     updated_at = models.DateTimeField(auto_now = True)

class booksDBManager(models.Manager):
    def createBook(self,postData):
         errors=[]
         if(postData['book_title']==""):
             errors.append('Please enter a title')
             return(False,errors)
         else:
             createdUser=userDB.objects.get(id=postData['id'])
             existingAuthor=Author.objects.get(id=postData['author'])
             if(existingAuthor):
                newAuthor=existingAuthor
             else:
                newAuthor=Author(name=postData['author_name'])
                newAuthor.save()
             newBook=Books(title=postData['book_title'],author=newAuthor)
             newBook.save()
             newReview=Reviews(review=postData['review'],rating=postData['rating'],book_rating=newBook,user_rating=createdUser)
             newReview.save()
             return(True,newBook)

class Books(models.Model):
    title = models.CharField(max_length=50)
    author = models.ForeignKey(Author)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    def __str__(self):
        return "title :"+self.title+"publishes date :"+str(self.published_date)
    def get_book_rating(self):
        revBook=Reviews.objects.filter(book_rating=self)
        return revBook
    objects=booksDBManager()

class reviewsDBManager(models.Manager):
    def createReview(self,postData):
        pass
    def updateReview(self,postData,id):
        errors=[]
        if(postData['review']=="") or (postData['rating']==""):
            errors.append('Please enter a review and rating')
            return(False,errors)
        else:
            reviewingUser=userDB.objects.get(id=postData['id'])
            reviewingBook=Books.objects.get(id=id)
            newReview=Reviews(review=postData['review'],rating=postData['rating'],book_rating=reviewingBook,user_rating=reviewingUser)
            newReview.save()
            return(True,newReview)

class Reviews(models.Model):
    review = models.CharField(max_length=50)
    rating = models.IntegerField()
    book_rating=models.ForeignKey(Books,related_name='rating_book')
    user_rating=models.ForeignKey(userDB,related_name='rating_user')
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    def get_rating_list(self):
        listRate=[]
        for item in range(self.rating):
            listRate.append(item)
        return listRate
    def get_rating_list_white(self):
        listRate=[]
        for item in range(5-self.rating):
            listRate.append(item)
        return listRate

    objects=reviewsDBManager()

apps/books_app/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib import messages
from django.shortcuts import render,redirect
from .models import Books
from .models import Author,userDB,Books,Reviews
# Create your views here.
def index(request):
    return render(request,'books_app/index.html')

def reg_home(request):
    return render(request,'books_app/registration.html')

def register(request):
    if( request.method=='POST'):
        ret_val=userDB.objects.register(request.POST)
        print ret_val
        if ret_val[0]:
            #newusers=userDB.objects.all()
            newusers=ret_val[1]
            request.session['user']={
                'id':newusers.id,
                'first_name':newusers.first_name,
                'last_name':newusers.last_name
            }
            context={
                "users": newusers
            }
            messages.add_message(request,messages.INFO,"Registered successfully!")
            return render(request,'books:books',context)
        else:
            for error in ret_val[1]:
                print error;
                messages.error(request,error)
            return redirect('books:reghome')

    return redirect('books:index')



def login(request):
    if( request.method=='POST'):
        ret_val=userDB.objects.login(request.POST)
        if ret_val[0]:
            print ret_val[1].id
            newusers=ret_val[1]
            #newusers=userDB.objects.get(id=ret_val[1].id)
            request.session['user']={
                'id':newusers.id,
                'first_name':newusers.first_name,
                'last_name':newusers.last_name
            }
            context={
                "users": newusers
            }
            print request.session['user']
            messages.add_message(request,messages.INFO,"Logged in successfully!")
            return redirect('books:books')
        else:
            for error in ret_val[1]:
                print error;
                messages.error(request,error)
            return redirect('books:index')

    return redirect('books:index')

def logout(request):
    request.session.clear()
    #userDB.objects.all.delete()
    return redirect('books:index')

def showAdd(request):
    context={
            "books":Books.objects.all(),
            "authors":Author.objects.all()
        }
    return render(request,'books_app/add.html',context)

def add(request):
    if( request.method=='POST'):
        print request.POST['author']
        ret_val=Books.objects.createBook(request.POST)
    if ret_val[0]:
        return redirect('books:showAdd')
    else:
        for error in ret_val[1]:
            print error;
            messages.error(request,error)
        return redirect('books:showAdd')
        context={
            "books":Books.objects.all(),
            "authors":Author.objects.all()
        }
    return redirect('books:books')

def books(request):
    context={
            "books":Books.objects.all(),
            "authors":Author.objects.all()
        }
    print "in index"
    return render(request,'books_app/books.html',context)

def review(request,id):
    context={
            "books":Books.objects.filter(id=id),
        }
    print "in review"
    return render(request,'books_app/review.html',context)

def update(request,id):
    if( request.method=='POST'):
        ret_val=Reviews.objects.updateReview(request.POST,id)
    if ret_val[0]:
        return redirect('books:books')
    else:
        for error in ret_val[1]:
            print error;
            messages.error(request,error)
        return redirect('books:review')
        context={
            "books":Books.objects.all(),
        }
    return redirect('books:books')

def users(request,id):
    pass

def newbook(request,id):
    if(request.method=="POST"):
        author_id=request.POST['author_id']
        a_id=Author.objects.get(id=int(author_id))
        newBook=Books(title=request.POST['book_title'],author=a_id,category=request.POST['book_category'])
        newBook.save()
    return redirect("/")

def newauthor(request):
    if(request.method=="POST"):
        newAuthor=Author.objects.create(first_name=request.POST['first_name'],last_name=request.POST['last_name'])
    return redirect("/")

apps/books_app/templates/books_app/add.html
<html>
<head>
  <meta char='utf-8'>
  <title>Books Review</title>
  {% load staticfiles %}
  <link rel="stylesheet" type="text/css" href="{% static 'books_app/css/style.css'%}" media="screen" title="no title"  charset="utf-8">
</head>
<body>
  {%if messages%}
  {% for message in messages%}
  <h4>{{ message }}</h4>
  {%endfor%}
  {%endif%}
  <form action={% url 'books:add' %} method="post">
    {% csrf_token %}
    <h1>Book details</h1>
    <input type='hidden' name="id" value="{{request.session.user.id}}">
    <table>
      <tbody>
        <tr>
          <td>Book Title:</td>
          <td><input type="text" name="book_title"></td>
        </tr>
        <tr><td>Author: </td></tr>
        <tr>
          <td>Choose from the list:</td>
          <td>
            <select name="author">
              {% if authors %}
              {% for author in authors %}
              <option value={{author.id}}>{{author.name}}</option>
              {%endfor%}
              {%endif%}
            </select>
          </td>
        </tr>
          <tr>
            <td>Add New Author</td>
            <td><input type="text" name="author_name"></td>
          </tr>
          <tr>
            <td>Review</td>
            <td><textarea rows=5 cols=50 name="review"></textarea></td>
          </tr>
          <tr>
            <td>Rating</td>
            <td>
              <select name="rating">
                <option value=1>1</option>
                <option value=2>2</option>
                <option value=3>3</option>
                <option value=4>4</option>
                <option value=5>5</option>
              </select>
              stars
            </td>
          </tr>
          <tr>
            <td><button type="submit" value="Add">Add Book and Review</button></td>
          </tr>
      </tbody>
      </table>
  </form>
</body>
</html>

apps/books_app/templates/books_app/books.html
<html>
<head>
  <meta char='utf-8'>
  <title>Books Review</title>
  {% load staticfiles %}
  <link rel="stylesheet" type="text/css" href="{% static 'books_app/css/style.css' %}" media="screen" title="no title"  charset="utf-8">
</head>
<body>
  <h1>Books</h1>
  {%if messages%}
  {% for message in messages%}
  <h4>{{ message }}</h4>
  {%endfor%}
  {%endif%}
  <section>
  <div id="first">
    <div id="left"><h4>Welcome, {{request.session.user.first_name}}, {{request.session.user.first_name}} </h4></div>
    <div id="middle"><a href={%url 'books:showAdd'%}>Add Book Review</a></div>
    <div id="right">logout</div>
  </div>
</section>
<section>
    <div id="leftreview">
      <h5>Recent Book reviews:</h5>
      {% for book in books %}
        <div>
        <a href={% url 'books:review' book.id %}>Title:{{book.title}}</a>
        </div>
        {% if book.get_book_rating %}
          {% for r in book.get_book_rating %}
          <div>
            Rating :
            {% for i in r.get_rating_list %}
              <img src="{% static 'books_app/img/yellowstar.png' %}" alt="">
            {% endfor %}
            {% for i in r.get_rating_list_white %}
              <img src="{% static 'books_app/img/whitestar.png' %}" alt="">
            {% endfor %}
            {{r.user_rating.first_name}} Says
            Review :{{r.review}}
            Posted on :{{r.created_at}}
          </div>
          {%endfor%}
        {%endif%}
        {%endfor%}
    </div>
    <div id="rightreview">
      Other Book with Reviews:
      <div id="table-wrapper">
        <div id="table-scroll">
          <table>
            {% for book in books %}
            <tr>
              <td>Title:{{book.title}}
              <a href={% url 'books:review' book.id %}>{{book.title}}</a>
              </td>
            </tr>
            {%endfor%}
          </table>
        </div>
      </div>
    </div>
</section>
</body>
</html>

apps/books_app/templates/books_app/index.html
<!DOCTYPE HTML>
<html>
<head>
  <meta char='utf-8'>
  <title>Users</title>
  {% load staticfiles %}
  <link rel="stylesheet" type="text/css" href="{% static 'books_app/css/style.css'%}" media="screen" title="no title"  charset="utf-8">
</head>
<body>
  {%if messages%}
  {% for message in messages%}
  <h4>{{ message }}</h4>
  {%endfor%}
  {%endif%}
  <form action={% url 'books:login' %} method="post">
    {%csrf_token%}
    <table>
      <tbody>
        <tr>
            <td>Your Email</td>
          <td><input type="text" name="email" value="newuser@test.com"></td>
        </tr>
        <tr>
            <td>Password</td>
          <td><input type="text" name="password" value="usertest12"></td>
        </tr>
        <tr>
          <td><button type="submit" name="login" value="login">Login</button></td>
        </tr>
      </tbody>
    </table>
  </form>
        <form action={% url 'books:reghome' %} method="post">
          {%csrf_token%}
          <table>
          </tbody>
          <tr>
          <td><button type="submit" name="register" value="register">Register</button></td>
          </tr>
      </tbody>
      </table>
    </form>
  </form>
</body>
</html>

apps/books_app/templates/books_app/registration.html
<!DOCTYPE HTML>
<html>
<head>
  <meta char='utf-8'>
  <title>Users</title>
  {% load staticfiles %}
  <link rel="stylesheet" type="text/css" href="{% static 'books_app/css/style.css'%}" media="screen" title="no title"  charset="utf-8">

</head>
<body>
  {% if messages %}
  {% for message in messages %}
    <div>{{ message }}</div>
  {% endfor %}
  {% endif %}
  <form action="{% url 'books:register' %}" method="post">
    {%csrf_token%}
    <table>
      <thead>
          <tr>
            <td>First Name:</td>
            <td>Last Name:</td>
            <td>email:</td>
            <td>Password</td>
            <td>Confirm Password</td>
          </tr>
      </thead>
      <tbody>
        <tr>
          <td><input type="text" name="first_name"></td>
          <td><input type="text" name="last_name"></td>
          <td><input type="text" name="email"></td>
          <td><input type="password" name="password"></td>
          <td><input type="password" name="confirm_pwd"></td>
          <td><button type="submit" value="register">Register</button></td>
        </tr>
      </table>
    </form>
</body>
</html>

apps/books_app/templates/books_app/review.html
<html>
<head>
  <meta char='utf-8'>
  <title>Add a Book Review</title>
  {% load staticfiles %}
  <link rel="stylesheet" type="text/css" href="{% static 'books_app/css/style.css' %}" media="screen" title="no title"  charset="utf-8">
</head>
<body>
  {%if messages%}
  {% for message in messages%}
  <h4>{{ message }}</h4>
  {%endfor%}
  {%endif%}
  {% for book in books %}
    <form action={% url 'books:update' book.id %} method="post">
      {% csrf_token %}
    <p>
    Book Title:{{book.title}}
    Author:{{book.author.name}}
  </p>
  <div>
    <h4>Reviews:</h4>
  </div>
    {% if book.get_book_rating %}
      {% for r in book.get_book_rating %}
        <div>
          <hr>
        Rating :
        {% for i in r.get_rating_list %}
          <img src="{% static 'books_app/img/yellowstar.png' %}" alt="">
        {% endfor %}
        {% for i in r.get_rating_list_white %}
          <img src="{% static 'books_app/img/whitestar.png' %}" alt="">
        {% endfor %}
        {{r.user_rating.first_name}} Says
        Review :{{r.review}}
        Posted on :{{r.created_at}}
      </div>
      {%endfor%}
    {%endif%}
    {%endfor%}
    <input type='hidden' name="id" value="{{request.session.user.id}}">
    <table>
    <tr>
    <td>Review</td>
      <td><textarea rows=5 cols=50 name="review"></textarea></td>
    </tr>
    <tr>
    <td>Rating</td>
    <td>
      <select name="rating">
        <option value=1>1</option>
        <option value=2>2</option>
        <option value=3>3</option>
        <option value=4>4</option>
        <option value=5>5</option>
      </select>
      stars
    </td>
    </tr>
    <tr>
      <td>
        <td><button type="submit" value="Add">Add Book and Review</button></td>
      </td>
    </tr>
    </table>
  </form>
</body>
</html>

apps/books_app/templates/books_app/success.html
<!DOCTYPE HTML>
<html>
<head>
  <meta char='utf-8'>
  <title>Users</title>
  {% load staticfiles %}
  <link rel="stylesheet" type="text/css" href="{% static 'log-reg/css/style.css'%}" media="screen" title="no title"  charset="utf-8">

</head></head>
<body>

  {%if messages%}
  {% for message in messages%}
  <h1>{{ message }}</h1>
  {%endfor%}
  {%endif%}

    <div>
      {{users.first_name}}
      {{users.last_name}}
      {{users.email}}
    </div>
  <h3><a href="/">back</a></h3>
</body>
</html>